Update maven example

diff --git a/docs/examples/maven.yml b/docs/examples/maven.yml
--- a/docs/examples/maven.yml
+++ b/docs/examples/maven.yml
@@ -5,7 +5,8 @@ utility:
     dest: /tmp
     # ignore the only condition if an upgrade is being performed
     only: '[ ! -e scratch/apache-maven ] || [ -n "${skip_checksum:-}" ]'
-    download: https://dlcdn.apache.org/maven/maven-3/${version}/binaries/apache-maven-${version}-bin.tar.gz
+    #download: https://dlcdn.apache.org/maven/maven-3/${version}/binaries/apache-maven-${version}-bin.tar.gz
+    download: https://repo1.maven.org/maven2/org/apache/maven/apache-maven/${version}/apache-maven-${version}-bin.tar.gz
     checksum_file: maven.sha256
     post_command: |
       # checksuming so skip post-download action
@@ -17,6 +18,17 @@ utility:
       ln -s apache-maven-"${version}" apache-maven
       rm /tmp/maven.tar.gz
     update: |
-      wget --quiet -O - https://dlcdn.apache.org/maven/maven-3 |
-      awk '$0 ~ /href="[0-9.]+/ { print gensub(/.*href="([0-9.]*).*/, "\\1", "g") }' |
-      sort -Vr | head -n1
+      # get update for maven-3
+      http_get() (
+        if type -P curl; then
+          curl -sSfL "$@"
+        elif type -P wget; then
+          wget --quiet -O - "$@"
+        else
+          echo 'No wget or curl found.  Cannot check for update.' >&2
+          return 1
+        fi
+      )
+      set -o pipefail
+      url=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/maven-metadata.xml
+      http_get "${url}" | grep -o '3\.[.0-9]\+' | sort -Vr | head -n1
